### ISSUE TITLE
Cleanup stratagus repo from bzr legacy

### ISSUE THREAD

**Issue by KroArtem** [Wargus/stratagus#158]
Since stratagus is now on GH, not launchad, it'd be a great idea to remove all bazaar stuff. There are several things to mention though: 
1) HOWTO-NEW-RELEASE refers to bazaar
2) /tools/genversion.cpp and /src/include/version.h also rely on bzr
3) CMakeLists.txt still has some bits about bzr
4) Some bits in documentation about bzr.

Whilst I can simply remove all bzr stuff, there are still questions on how do you want to handle new releases.

**Comment by timfel** [comment]
I have gone and removed bzr and launchpad references. However, how to handle new releases is still an open question. Right now there are many steps, I would like to eventually integrate it with the automatic build system, so that it will be as simple as updating the changelog and version number (and that should be in one place, not many)

**Comment by KroArtem** [comment]
There are still .bzr-builddeb and .bzrignore in the repo.

**Comment by KroArtem** [comment]
Just to be clear, there is a small memleak in tools/genversion.cpp: git_rev is allocated and is not freed.
Otherwise, this issue can be closed.
