### ISSUE TITLE
Wishes: stratagus games on android/ios

### ISSUE THREAD

**Issue by ilwar2** [Wargus/stratagus#188]
Hello, people, i'm admin on war2.ru project.
New people appears on our forums sometimes with requests about warcraft 2 on smartphones. Mobile phones is sufficient and fast growing part in our world. And many people would be happy to have warcraft 2 on their mobile phone.

But as i understood, all the implementations of wargus/stratagus on mobile phones are old, ugly and unofficial.
So, my wish about wargus project: to have support of the mobile platform together with last releases for win and unix. Of course, that means some interface changes, adaptation to touchscreen instead of hotkeys and mouse, but that should not cause serious changes in the heart of the game. That's why i don't mean android version as a separate fork or w/e, but just another configuration in the same project.

Do your team have any plans about mobile platforms?

**Comment by timfel** [comment]
Hi,
mobile apps would be awesome, but I don't think anybody has the time and the energy. we'd be happy to accept contributions, though. there already is touchscreen and zoom support for windows or linux tablets, so that click targets are large and the game can be played with touch. but figuring out how to compile on mobile platforms with opengles needs time.

**Comment by mimooh** [comment]
Highly unlikely that anyone would work on this anytime soon. Closing.
