### ISSUE TITLE
.vscode/settings.json causes CMake error on Linux

### ISSUE THREAD

**Issue by ipochto** [Wargus/stratagus#307]
`.vscode/settings.json` added in this 4ef8e5388845dc62a1964c32cd202ed3b30d170c commit contains settings only for Windows and causes error in VS Code on linux:
`CMake Error: Could not create named generator Visual Studio 16 2019`

Also my own `lanuch.json`  was overwritten.

Isn't `.vscode` contains settings and preferences for certain local copy of project and may differ from developer to developer?

**Comment by timfel** [comment]
In part yes, but I read through the MS docs for this and they considered committing the vscode folder as a valid use case. My goal was to make it easier for Windows users to get started, since that's been a recurring problem. I think we should try to make sure the settings don't break Linux settings, but I believe local settings should be stored in the workspace, and the project setting can be committed

**Comment by timfel** [comment]
Also, you said it overwrote your local settings? How's that possible, git should've complained that the pull conflicts with local untracked files and aborted. Did you force the checkout?

**Comment by ipochto** [comment]
I'm not very familiar with git, so yes - I was able to do some actions with `-f` switch )))
As I can remember I did `fetch upstream` (from wargus/stratagus) to `master`, then `rebase` my local branches which based on `master`. At least once `-f` was used - when pulled my local rebased branches to the github (forked repo).
That was done 2 or 3 times in last 3 months. But issue with .vscode was mentioned just now because I didn't compile stratagus a very long time.

**Comment by timfel** [comment]
I've been reviewing the CMake VSCode docs, and it should be possible to change the settings to work on both windows and other platforms. Also the "download dependencies" task can be made platform independent. I will try to it, but I won't have time until the weekend. Unless you have time and want to do it :-)

**Comment by ipochto** [comment]
Do you mean do it via cmake variants? https://vector-of-bool.github.io/docs/vscode-cmake-tools/variants.html#variants

```
cmake.configureArgs
Arguments to CMake that will be passed during the configure process.

Default: [] (Empty array, no arguments)

Supports substitution

Warning Always prefer to use cmake.configureSettings or CMake Variants. Never pass -D arguments using this setting.
```

**Comment by timfel** [comment]
I was thinking instead to use the 'preferredGenerators' setting rather than just forcing a generator, this way it should use it on windows, but on Linux where it's not available it'll just ignore that. I think the platform and toolset options are windows specific anyway, so maybe they'll just be ignored on windows. The STDIO_REDIRECT option should just be set for Windows within the CMakeList.txt. Only for the CMAKE_PREFIX_PATH I'm not sure, but we can potentially pass it as a custom define variable unconditionally on all platforms, and within the CMakeList.txt we translate it to CMAKE_PREFIX_PATH only for Windows

**Comment by timfel** [comment]
@ipochto does this work? https://github.com/Wargus/stratagus/pull/308

**Comment by ipochto** [comment]
@timfel, yes, it works now. Not sure about folders in launch.json (can't check now), but make and build are fixed. Thanks.

**Comment by timfel** [comment]
PRs are merged.
